### ISSUE TITLE
Analizar y comprender el problema

### ISSUE THREAD

**Issue by Tomasposada26** [Tomasposada26/DesarrolloDeSoftware#1]
En esta primera actividad participaremos en conjunto todos los miembros del equipo para entablar una misma ruta hacia la que va dirigida el proyecto

**Comment by Tomasposada26** [comment]
a

**Comment by miguelhernandez18** [comment]
[ANÁLISIS EADRIVE.docx](https://github.com/Tomasposada26/DesarrolloDeSoftware/files/12457596/ANALISIS.EADRIVE.docx)
